<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="appsettings.json" />
    <None Remove="Resources\icon.ico" />
    <None Remove="Resources\Images\1.JPG" />
    <None Remove="Resources\Images\10.JPG" />
    <None Remove="Resources\Images\2.JPG" />
    <None Remove="Resources\Images\3.JPG" />
    <None Remove="Resources\Images\4.JPG" />
    <None Remove="Resources\Images\5.JPG" />
    <None Remove="Resources\Images\6.JPG" />
    <None Remove="Resources\Images\7.JPG" />
    <None Remove="Resources\Images\8.JPG" />
    <None Remove="Resources\Images\9.JPG" />
    <None Remove="Resources\logo.png" />
    <None Remove="Resources\picture.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.8" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\icon.ico" />
    <Resource Include="Resources\Images\1.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\10.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\2.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\3.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\4.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\5.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\6.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\7.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\8.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\Images\9.JPG">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Resource>
    <Resource Include="Resources\logo.png" />
    <Resource Include="Resources\picture.png" />
  </ItemGroup>

</Project>
